FROM alpine
WORKDIR /usr/src/app
RUN apk add --no-cache gcc make libc-dev tcpdump
# RUN apk add --no-cache cmake 

COPY --from=scripts . /scripts
COPY . .
# RUN ln -s /usr/bin/gcc /usr/bin/cc
# RUN cmake -Bbuild
# RUN cmake --build build
RUN make
CMD ["./main"]
